# configs/ddpg.yaml

# Gymnasium environment settings
env:
  #name: CartPole-v1
  name: LunarLander-v3
  #max_steps: 250  # Level 2: Change number of steps per episode (trajectory)

# Random seed for reproducibility
seed: 422

# Agent hyperparameters
agent:
  lr_actor: 0.0001
  lr_critic: 0.001
  gamma: 0.99
  tau: 0.001
  hidden_size: 256
  batch_size: 64
  expl_noise: 0.1

# Training settings
train:
  episodes: 500        # total episodes to train
  eval_interval: 20     # how often (in episodes) to run evaluation
  eval_episodes: 5      # number of episodes to evaluate
